# Autogenerate a release with changelog using Github workflow
# https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
# Variables in here are pulled from Github automatically (do not need to be manually set elsewhere)
# https://docs.github.com/en/actions/learn-github-actions/variables#using-the-env-context-to-access-environment-variable-values

name: Create Changelog

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          wget -O git-chglog.tar.gz \
          https://github.com/git-chglog/git-chglog/releases/download/v0.15.1/git-chglog_0.15.1_linux_amd64.tar.gz && \
          tar -xvf git-chglog.tar.gz git-chglog && \
          chmod 755 git-chglog

          echo 'CHANGELOG<<EOF' >> $GITHUB_ENV
          ./git-chglog --config .chglog/config.yml --next-tag Unreleased ${{ github.ref_name }} >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: get repository name
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - name: Create release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ env.REPOSITORY_NAME }} ${{ github.ref }}
          body: ${{ env.CHANGELOG }}git stat
